# Generated by Django 3.2.9 on 2021-11-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='UserMaster',
        ),
    ]
